version: '3'

networks:
  carnival:
    driver: bridge
    external: false

services:
  nginx:
    image: nginx:alpine
    networks:
      carnival:

    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname==worker02
